all:
	g++ ./Server/server.cpp -g -Wall -o ./server
	g++ ./Server/server_select.cpp -g -Wall -o ./server_select
	g++ ./Server/server_threaded.cpp -g -Wall -pthread -o ./server_threaded
	g++ ./Client/client.cpp -g -Wall -o ./client
